apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels: {{ include "k8s-prometheus-adapter.labels" . | nindent 4 }}
  name: {{ template "k8s-prometheus-adapter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    app: {{ template "k8s-prometheus-adapter.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}

