{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "k8s-prometheus-adapter.labels" . | nindent 4 }}
  name: {{ template "k8s-prometheus-adapter.name" . }}-resource-reader
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
{{- end -}}
