{{- if and .Values.rbac.create .Values.rules.external -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "k8s-prometheus-adapter.labels" . | nindent 4 }}
  name: {{ template "k8s-prometheus-adapter.name" . }}-external-metrics
rules:
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
{{- end -}}
