{{- if and .Values.rbac.create .Values.rules.resource -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "k8s-prometheus-adapter.labels" . | nindent 4 }}
  name: {{ template "k8s-prometheus-adapter.name" . }}-metrics
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/stats
  verbs:
  - get
  - list
  - watch
{{- end -}}
